/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinemore.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinemore.controller.ManageAddReceptionController;
import lk.ijse.dinemore.dto.AddReceptionDTO;
import lk.ijse.dinemore.observer.Observer;

/**
 *
 * @author ACER
 */
public class AddReceptionView extends javax.swing.JPanel implements Observer{
    private String reservedRecID="";

    /**
     * Creates new form AddReception
     */
    public AddReceptionView(){
        try {
            initComponents();
//            loadAllReception();
            UnicastRemoteObject.exportObject(this, 0);
            ManageAddReceptionController.getSubeject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(AddReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadAllReception() {
        DefaultTableModel dtm = (DefaultTableModel) tblReception.getModel();
        dtm.setRowCount(0);
        try {
            List<AddReceptionDTO> receptions = ManageAddReceptionController.getAllReception();
            if (receptions == null) {
                return;
            }

            for (AddReceptionDTO addReceptionDTO : receptions) {
                Object[] rowData = {
                    addReceptionDTO.getRecID(),
                    addReceptionDTO.getRecName(),
                    addReceptionDTO.getRecNic(),
                    addReceptionDTO.getRecAddress()
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(AddReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRecAdderss = new javax.swing.JTextField();
        txtRecName = new javax.swing.JTextField();
        txtRecNic = new javax.swing.JTextField();
        txtRecID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReception = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(96, 83, 150));
        jLabel7.setText("Reception ID");
        pnlLoad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 124, 41));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(96, 83, 150));
        jLabel10.setText("Reception Name");
        pnlLoad.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 124, 41));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(96, 83, 150));
        jLabel12.setText("Reception Address");
        pnlLoad.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 124, 30));
        pnlLoad.add(txtRecAdderss, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 280, 40));
        pnlLoad.add(txtRecName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 280, 40));
        pnlLoad.add(txtRecNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 280, 40));

        txtRecID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecIDActionPerformed(evt);
            }
        });
        pnlLoad.add(txtRecID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 280, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 83, 150));
        jLabel13.setText("Reception NIC");
        pnlLoad.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 124, 30));

        tblReception.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reception ID", "Reception Name", "NIC", "Address"
            }
        ));
        jScrollPane1.setViewportView(tblReception);

        pnlLoad.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 550, 90));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlLoad.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlLoad.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlLoad.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        btnSearch.setText("Search");
        pnlLoad.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        add(pnlLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            AddReceptionDTO addReceptionDTO=new AddReceptionDTO(
                    txtRecID.getText(),
                    txtRecName.getText(),
                    txtRecNic.getText(),
                    txtRecAdderss.getText()
            );
            boolean addReception=ManageAddReceptionController.addReception(addReceptionDTO);
            if (addReception) {
                JOptionPane.showMessageDialog(this, "Reception has been Added Successfully");
                loadAllReception();
                clearText();
            }
        } catch (Exception ex) {
            Logger.getLogger(AddReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            boolean removeReception = ManageAddReceptionController.deleteReception(txtRecID.getText());
            if (removeReception) {
                JOptionPane.showMessageDialog(this, "Reception has been Delete Successfully");
                loadAllReception();
                clearText();
            }else {
                JOptionPane.showMessageDialog(this, "Not Found ");
            }
        } catch (Exception ex) {
            Logger.getLogger(AddReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            AddReceptionDTO addReceptionDTO=new AddReceptionDTO(
                    txtRecID.getText(),
                    txtRecName.getText(),
                    txtRecNic.getText(),
                    txtRecAdderss.getText()
            );
            boolean deleteReception=ManageAddReceptionController.updateReception(addReceptionDTO);
            if (deleteReception) {
                JOptionPane.showMessageDialog(this, "Reception has been Delete Successfully");
                loadAllReception();
                clearText();
            }else {
                JOptionPane.showMessageDialog(this, "Not Found ");
            }
        } catch (Exception ex) {
            Logger.getLogger(AddReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlLoad;
    private javax.swing.JTable tblReception;
    private javax.swing.JTextField txtRecAdderss;
    private javax.swing.JTextField txtRecID;
    private javax.swing.JTextField txtRecName;
    private javax.swing.JTextField txtRecNic;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadAllReception();
    }
    
    public void clearText(){
        txtRecID.setText("");
        txtRecName.setText("");
        txtRecNic.setText("");
        txtRecAdderss.setText("");
    }
}
