/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinemore.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinemore.controller.ManageChefController;
import lk.ijse.dinemore.controller.ManageReceptionController;
import lk.ijse.dinemore.dto.ReceptionDTO;
import lk.ijse.dinemore.observer.Observer;

/**
 *
 * @author ACER
 */
public class chefView extends javax.swing.JFrame implements Observer{
//    private String reservedOrderID ="";

    /**
     * Creates new form chefView
     */
    public chefView(){
        try {
            initComponents();
            loadAllOrder();
            UnicastRemoteObject.exportObject(this, 0);
            ManageReceptionController.getSubeject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(chefView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private DefaultTableModel dtm;
    
    private void loadAllOrder() {
        dtm = (DefaultTableModel) tblOrder1.getModel();
        dtm.setRowCount(0);
        try {
            List<ReceptionDTO> receptions = ManageReceptionController.getAllOrder();
            if (receptions == null) {
                return;
            }

            for (ReceptionDTO receptionDTO : receptions) {
                Object[] rowData = {
                    receptionDTO.getOrderID(),
                    receptionDTO.getCustomerName(),
                    receptionDTO.getTPNumber(),
                    receptionDTO.getQty(),
                    receptionDTO.getDate(),
                    receptionDTO.getTime(),
                    "1"
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(ReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        btnCook = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtOID = new javax.swing.JLabel();
        txtTp = new javax.swing.JLabel();
        txtQty = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/dinemore/assest/Chef_50px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 40));

        tblOrder1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OID", "Name", "TP", "QTY", "Date", "Time"
            }
        ));
        tblOrder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrder1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrder1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 1040, 310));

        jLabel2.setBackground(new java.awt.Color(255, 255, 51));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Reception Orders");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 310, 40));

        btnFinish.setBackground(new java.awt.Color(0, 153, 204));
        btnFinish.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnFinish.setForeground(new java.awt.Color(255, 255, 255));
        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 200, 30));

        btnCook.setBackground(new java.awt.Color(0, 0, 102));
        btnCook.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCook.setForeground(new java.awt.Color(255, 255, 255));
        btnCook.setText("Cook");
        btnCook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        jPanel1.add(btnCook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/dinemore/assest/cookss.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 630));

        jLabel1.setBackground(new java.awt.Color(51, 0, 102));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chef");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        txtTime.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("Time");
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 459, 60, 30));

        txtOID.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtOID.setForeground(new java.awt.Color(255, 255, 255));
        txtOID.setText("OrderID");
        jPanel1.add(txtOID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 60, 30));

        txtTp.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtTp.setForeground(new java.awt.Color(255, 255, 255));
        txtTp.setText("TP Number");
        jPanel1.add(txtTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 100, 30));

        txtQty.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtQty.setForeground(new java.awt.Color(255, 255, 255));
        txtQty.setText("Qty");
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 50, 30));

        txtDate.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("Date");
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 70, 30));

        txtName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Customer Name");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookActionPerformed
       try {
           String status = "Cooking";
            ReceptionDTO receptionDTO = new ReceptionDTO(
                txtOID.getText(),
                txtName.getText(),
                txtTp.getText(),
                Integer.parseInt(txtQty.getText()),
                txtDate.getText(),
                txtTime.getText(),
                status
            );
            boolean cooking = ManageChefController.updateCooking(receptionDTO);
            if (cooking) {
                JOptionPane.showMessageDialog(this, "Take Order Successfully");
                loadAllOrder();
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Failed Take Order");
            }
//            ManageReceptionController.releaseCustomer(reservedOrderID);
//            reservedOrderID="";
        } catch (Exception ex) {
            Logger.getLogger(ReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCookActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
       try {
           String status = "Finish";
            ReceptionDTO receptionDTO = new ReceptionDTO(
                txtOID.getText(),
                txtName.getText(),
                txtTp.getText(),
                Integer.parseInt(txtQty.getText()),
                txtDate.getText(),
                txtTime.getText(),
                status
            );
            boolean cooking = ManageChefController.updateCooking(receptionDTO);
            if (cooking) {
                JOptionPane.showMessageDialog(this, "Cooked");
                loadAllOrder();
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Failed Cooking");
            }
//            ManageReceptionController.releaseCustomer(reservedOrderID);
//            reservedOrderID="";
        } catch (Exception ex) {
            Logger.getLogger(ReceptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void tblOrder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrder1MouseClicked
        int selectedRow=tblOrder1.getSelectedRow();
        String oid=dtm.getValueAt(selectedRow, 0).toString();
        String name=dtm.getValueAt(selectedRow, 1).toString();
        String tp=dtm.getValueAt(selectedRow, 2).toString();
        String qty=dtm.getValueAt(selectedRow, 3).toString();
        String date=dtm.getValueAt(selectedRow, 4).toString();
        String time=dtm.getValueAt(selectedRow, 5).toString();
        
        txtOID.setText(oid);
        txtName.setText(name);
        txtTp.setText(tp);
        txtQty.setText(qty);
        txtDate.setText(date);
        txtTime.setText(time);
        
    }//GEN-LAST:event_tblOrder1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chefView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chefView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chefView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chefView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new chefView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCook;
    private javax.swing.JButton btnFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder1;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtOID;
    private javax.swing.JLabel txtQty;
    private javax.swing.JLabel txtTime;
    private javax.swing.JLabel txtTp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadAllOrder();
        
    }
    
    public void clearText(){
        txtOID.setText("");
        txtName.setText("");
        txtTp.setText("");
        txtQty.setText("");
        txtTime.setText("");
        txtDate.setText("");
    }
}
